Regex All

In [1]:
import re

text = "I have 2 apples and 15 oranges"

numbers = re.findall(r'\d+', text) #Find all numbers

print(numbers)

['2', '15']


In [2]:
import re

text = "Emails: test806@gmail.com, user@yahoo23.com"

emails = re.findall(r'\w+\d+@\w+\.\w+', text)   #Email find korbe

print(emails)

['test806@gmail.com']


In [3]:
import re

text = "I like cat"

new_text = re.sub(r'cat', 'dog', text)      #Replace korbe

print(new_text)

I like dog


In [7]:
import re

password=input()

pattern = r'[a-z][A-Z]+\d+'      #Validate Check

if re.match(pattern, password):
    print("Valid password")
else:
    print("Invalid")

Invalid


In [8]:
import re

text = "Today is 2026-03-15"

date = re.findall(r'\d{4}-\d{2}-\d{2}', text)         #Date diye exact number khuja

print(date)

['2026-03-15']


Error Exception

In [15]:
try:
    num = int(input("Enter a number: "))
    print("Valid number:",num)      #Specific Check

except ValueError:
    print("Invalid number")

Invalid number


In [18]:
try:
    a = int(input())
    b = int(input())
    print(a / b)

except ZeroDivisionError:
    print("Cannot divide by zero")      #Multiple error

except ValueError:
    print("Invalid input")

0.6666666666666666


In [19]:
try:
    a = 10
    b = 0
    print(a / b)

except ZeroDivisionError:
    print("0 দিয়ে ভাগ করা যায় না")

else:
    print("Division successful")        #except kaj na korle

finally:
    print("Program finished")

0 দিয়ে ভাগ করা যায় না
Program finished


In [20]:
try:
    num = int(input("Enter number: "))      #ValueError
    print(num)

except ValueError:
    print("Number ছাড়া অন্য কিছু দেওয়া হয়েছে")

else:
    print("Input correct")

finally:
    print("Done")

Number ছাড়া অন্য কিছু দেওয়া হয়েছে
Done


In [22]:
try:
    result = 5 + "10"
    print(result)                   #TypeError

except TypeError:
    print("Different data type add করা যাবে না")

finally:
    print("Finished")

Different data type add করা যাবে না
Finished


In [23]:
try:
    numbers = [10,20,30]
    print(numbers[5])

except IndexError:                  #IndexError
    print("List এ এই index নেই")

finally:
    print("Program end")

List এ এই index নেই
Program end


In [ ]:
try:
    numbers = [10,20,30]
    print(numbers[5])

except IndexError:                  #Index Error
    print("List এ এই index নেই")

finally:
    print("Program end")

In [24]:
try:
    student = {"name":"Rahim","age":20}
    print(student["id"])

except KeyError:
    print("এই key dictionary তে নেই")                   #Key Dict

finally:
    print("Done")

এই key dictionary তে নেই
Done


In [26]:
try:
    file = open("data.txt","r")         #FileNotFoundError
    print(file.read())

except FileNotFoundError:
    print("File পাওয়া যায়নি")

finally:
    print("File check complete")

File পাওয়া যায়নি
File check complete


Numpy

In [27]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2D Array

In [28]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


Indexing

In [29]:
arr = np.array([10,20,30,40])

print(arr[1])

20


Array Shape

In [30]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)

(2, 3)


Special Array Functions

In [31]:
arr = np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


Range Array

In [32]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


Random Numbers

In [33]:
arr = np.random.rand(3)
print(arr)

[0.50037219 0.94636364 0.20792811]


Array Operations

In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)

[5 7 9]


Mean & Sum

In [35]:
arr = np.array([10,20,30,40])

print(np.sum(arr))
print(np.mean(arr))

100
25.0


Reshape

In [36]:
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


Input

In [40]:
arr = np.array(input("Enter numbers: ").split())

print(arr)

['1' '2' '3' '4']


Loop দিয়ে input array

In [41]:
n = int(input("Size: "))

data = []

for i in range(n):
    x = int(input())
    data.append(x)

arr = np.array(data)

print(arr)

[1 2 3]


2D Input Array

In [42]:
rows = int(input("Rows: "))
cols = int(input("Cols: "))

data = []

for i in range(rows):
    row = list(map(int, input().split()))
    data.append(row)

arr = np.array(data)

print(arr)

[[1]
 [2]
 [3]]


HackerRank Numpy

In [58]:
new_arr=[]
def arrays(arr):
    arr = np.array(arr, float)
    arr=arr[::-1]
    return arr


arr = input().strip().split(' ')
result = arrays(arr)
print(result)

[-10.  -8.   4.   3.   2.   1.]


HackerRank Reshape

In [67]:
import numpy as np
arr=input().split()
arr = np.array(arr,int)
new_arr=arr.reshape(3,3)
print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


HackerRank Martix

In [80]:
n, m = map(int, input().split())
data = []

for i in range(n):
    row = list(map(int, input().split()))
    data.append(row)
arr = np.array(data)
print(arr.transpose())
print(arr.flatten())

[[1 3]
 [2 4]]
[1 2 3 4]


In [82]:
import numpy as np

shape = list(map(int, input().split()))

print(np.zeros(shape, dtype=int))
print(np.ones(shape, dtype=int))

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


Class Inheritance

In [83]:
class Animal:
    def sound(self):
        print("Animal sound")

class Dog(Animal):
    pass

d = Dog()
d.sound()

Animal sound


Polymorphism

In [84]:
class Bird:
    def fly(self):
        print("Bird can fly")

class Penguin:
    def fly(self):
        print("Penguin cannot fly")

b = Bird()
p = Penguin()

b.fly()
p.fly()

Bird can fly
Penguin cannot fly


Encapsulation

In [85]:
class Student:
    def __init__(self):
        self.__marks = 80

    def show(self):
        print(self.__marks)

s = Student()
s.show()

80
